In [1]:
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

In [2]:
# import os
# proxy = 'http://127.0.0.1:7897'
# os.environ['HTTP_PROXY'] = proxy
# os.environ['HTTPS_PROXY'] = proxy

In [3]:
import yfinance as yf

In [4]:
start_date = '2010-12-01'
end_date = '2025-12-31'
dat = yf.download('JPM', start = start_date, end = end_date, interval = '1mo')

[*********************100%***********************]  1 of 1 completed

In [5]:
dat

Price            Close        High         Low        Open     Volume
Ticker             JPM         JPM         JPM         JPM        JPM
Date
2010-12-01   28.245085   28.711176   25.069013   25.268766  665999200
2011-01-01   29.923002   30.588846   28.398223   28.631267  827482200
2011-02-01   31.123951   32.237189   29.530757   30.130706  597586300
2011-03-01   30.730650   31.397258   28.930809   30.977297  684643600
2011-04-01   30.417341   31.863880   29.017462   31.030620  577996200
...                ...         ...         ...         ...        ...
2025-08-01  298.614716  300.130475  281.594586  287.697259  148828400
2025-09-01  312.494293  315.050298  288.727577  297.465497  182562300
2025-10-01  308.224396  311.662102  287.835947  311.047877  189429800
2025-11-01  311.674103  320.802938  291.495136  309.603456  150218700
2025-12-01  320.773071  329.374258  297.119756  311.544709  211615600

[181 rows x 5 columns]

In [6]:
dat['r'] = dat['Close'] / dat['Close'].shift(1) - 1
dat = dat.dropna()
dat['r']

Date
2011-01-01    0.059406
2011-02-01    0.040135
2011-03-01   -0.012637
2011-04-01   -0.010195
2011-05-01   -0.047239
                ...
2025-08-01    0.022388
2025-09-01    0.046480
2025-10-01   -0.013664
2025-11-01    0.011192
2025-12-01    0.029194
Name: r, Length: 180, dtype: float64

In [7]:
FF_all = pd.read_csv('FF_Factors_mo.csv',header=3)
FF_all

      Month  Mkt-RF   SMB   HML   RMW   CMA    RF
0    196307   -0.39 -0.48 -0.81  0.64 -1.15  0.27
1    196308    5.08 -0.80  1.70  0.40 -0.38  0.25
2    196309   -1.57 -0.43  0.00 -0.78  0.15  0.27
3    196310    2.54 -1.34 -0.04  2.79 -2.25  0.29
4    196311   -0.86 -0.85  1.73 -0.43  2.27  0.27
..      ...     ...   ...   ...   ...   ...   ...
745  202508    1.85  4.88  4.42 -0.68  2.08  0.38
746  202509    3.39 -2.18 -1.05 -2.06 -2.22  0.33
747  202510    1.96 -1.31 -3.09 -5.21 -4.03  0.37
748  202511   -0.13  1.47  3.76  1.42  0.68  0.30
749  202512   -0.36 -0.22  2.42  0.40  0.37  0.34

[750 rows x 7 columns]

In [8]:
FF = FF_all[lambda df: df['Month']>=201101]    # FF = FF_all[FF_all['Month']>=201012]
FF

      Month  Mkt-RF   SMB   HML   RMW   CMA    RF
570  201101    1.98 -2.31  0.61 -0.64  0.81  0.01
571  201102    3.48  1.65  1.18 -1.83  0.84  0.01
572  201103    0.46  2.56 -1.84  1.73 -0.07  0.01
573  201104    2.90 -0.53 -2.44  1.12 -0.86  0.00
574  201105   -1.27 -0.72 -1.85  1.92 -1.43  0.00
..      ...     ...   ...   ...   ...   ...   ...
745  202508    1.85  4.88  4.42 -0.68  2.08  0.38
746  202509    3.39 -2.18 -1.05 -2.06 -2.22  0.33
747  202510    1.96 -1.31 -3.09 -5.21 -4.03  0.37
748  202511   -0.13  1.47  3.76  1.42  0.68  0.30
749  202512   -0.36 -0.22  2.42  0.40  0.37  0.34

[180 rows x 7 columns]

In [9]:
FF['JPM'] = dat['r'].values * 100 - FF['RF'].values

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15052\3315324307.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FF['JPM'] = dat['r'].values * 100 - FF['RF'].values

In [10]:
FF = FF.set_index('Month')
FF

        Mkt-RF   SMB   HML   RMW   CMA    RF       JPM
Month
201101    1.98 -2.31  0.61 -0.64  0.81  0.01  5.930565
201102    3.48  1.65  1.18 -1.83  0.84  0.01  4.003463
201103    0.46  2.56 -1.84  1.73 -0.07  0.01 -1.273660
201104    2.90 -0.53 -2.44  1.12 -0.86  0.00 -1.019532
201105   -1.27 -0.72 -1.85  1.92 -1.43  0.00 -4.723885
...        ...   ...   ...   ...   ...   ...       ...
202508    1.85  4.88  4.42 -0.68  2.08  0.38  1.858793
202509    3.39 -2.18 -1.05 -2.06 -2.22  0.33  4.317988
202510    1.96 -1.31 -3.09 -5.21 -4.03  0.37 -1.736392
202511   -0.13  1.47  3.76  1.42  0.68  0.30  0.819219
202512   -0.36 -0.22  2.42  0.40  0.37  0.34  2.579385

[180 rows x 7 columns]

In [11]:
FF.to_csv('FFmodel_data.csv')

In [12]:
df_train = FF[lambda df: df.index<=202012] # In-Sample performance
df_test = FF[lambda df: df.index>202012] # Out-of-Sample performance

Q(1) single-factor-model

In [13]:
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [14]:
Y = df_train['JPM']
X = df_train['Mkt-RF']
X

Month
201101     1.98
201102     3.48
201103     0.46
201104     2.90
201105    -1.27
          ...
202008     7.62
202009    -3.64
202010    -2.08
202011    12.44
202012     4.63
Name: Mkt-RF, Length: 120, dtype: float64

In [15]:
X = sm.add_constant(X)
X

        const  Mkt-RF
Month
201101    1.0    1.98
201102    1.0    3.48
201103    1.0    0.46
201104    1.0    2.90
201105    1.0   -1.27
...       ...     ...
202008    1.0    7.62
202009    1.0   -3.64
202010    1.0   -2.08
202011    1.0   12.44
202012    1.0    4.63

[120 rows x 2 columns]

In [16]:
model_s = sm.OLS(Y, X)
results_s = model_s.fit()

In [17]:
print(results_s.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    JPM   R-squared:                       0.567
Model:                            OLS   Adj. R-squared:                  0.564
Method:                 Least Squares   F-statistic:                     154.6
Date:                Sat, 28 Feb 2026   Prob (F-statistic):           3.37e-23
Time:                        15:03:11   Log-Likelihood:                -357.78
No. Observations:                 120   AIC:                             719.6
Df Residuals:                     118   BIC:                             725.1
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.1655      0.456     -0.363      0.717      -1.069       0.738
Mkt-RF         1.3325      0.107     12.435      0.000       1.120       1.545
==============================================================================
Omnibus:                        0.260   Durbin-Watson:                   2.022
Prob(Omnibus):                  0.878   Jarque-Bera (JB):                0.044
Skew:                          -0.013   Prob(JB):                        0.978
Kurtosis:                       3.091   Cond. No.                         4.44
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [18]:
results_s.params[0]

-0.16551601871389593

Point estimation of alpha = -0.1655, and P = 0.717 > 0.05, so we cannot reject H0: alpha = 0.
Therefore, alpha is NOT nonzero in the sampling period.

In [19]:
results_s.params[1]

1.3324960495827858

Point estimation of beta = 1.3325 > 1, and P = 0.000 < 0.01 with t = 12.435, so we can affirm that beta > 1 and JPM is a cyclical stock.

In [20]:
results_s.rsquared

0.5671693398555548

R square is 0.567, so this model explains 56.7% total variation of the single-factor model.

Q(2) three-factor-model

In [21]:
Y = df_train['JPM']
X = df_train[['Mkt-RF','SMB','HML']]
X = sm.add_constant(X)
model_ff3 = sm.OLS(Y, X)
results_ff3 = model_ff3.fit()
print(results_ff3.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    JPM   R-squared:                       0.698
Model:                            OLS   Adj. R-squared:                  0.691
Method:                 Least Squares   F-statistic:                     89.53
Date:                Sat, 28 Feb 2026   Prob (F-statistic):           4.68e-30
Time:                        15:03:14   Log-Likelihood:                -336.11
No. Observations:                 120   AIC:                             680.2
Df Residuals:                     116   BIC:                             691.4
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.4597      0.396      1.161      0.248      -0.324       1.244
Mkt-RF         1.1938      0.100     11.894      0.000       0.995       1.393
SMB            0.0159      0.171      0.093      0.926      -0.323       0.355
HML            1.0159      0.150      6.782      0.000       0.719       1.313
==============================================================================
Omnibus:                        9.220   Durbin-Watson:                   2.240
Prob(Omnibus):                  0.010   Jarque-Bera (JB):               12.722
Skew:                          -0.394   Prob(JB):                      0.00173
Kurtosis:                       4.387   Cond. No.                         4.83
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [22]:
results_ff3.params[0]

0.45973625346798314

Point estimation of alpha = 0.4597, and P = 0.248 > 0.05, so we cannot reject H0: alpha = 0. Therefore, alpha is NOT nonzero in the sampling period.

In [23]:
results_ff3.rsquared

0.6983716126246098

R square is 0.698 now compared with 0.567 estimated in the single-factor model, so the Fama-French model explains 13.1% more total variation than the single-factor model.

Q(3) five-factor-model

In [24]:
Y = df_train['JPM']
X = df_train[['Mkt-RF','SMB','HML','RMW','CMA']]
X = sm.add_constant(X)
model_ff5 = sm.OLS(Y, X)
results_ff5 = model_ff5.fit()
print(results_ff5.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    JPM   R-squared:                       0.770
Model:                            OLS   Adj. R-squared:                  0.760
Method:                 Least Squares   F-statistic:                     76.39
Date:                Sat, 28 Feb 2026   Prob (F-statistic):           9.14e-35
Time:                        15:03:15   Log-Likelihood:                -319.80
No. Observations:                 120   AIC:                             651.6
Df Residuals:                     114   BIC:                             668.3
Df Model:                           5
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6483      0.350      1.851      0.067      -0.046       1.342
Mkt-RF         1.1586      0.091     12.749      0.000       0.979       1.339
SMB           -0.3591      0.164     -2.192      0.030      -0.684      -0.035
HML            1.3326      0.159      8.385      0.000       1.018       1.647
RMW           -1.1914      0.229     -5.193      0.000      -1.646      -0.737
CMA           -0.7596      0.275     -2.767      0.007      -1.303      -0.216
==============================================================================
Omnibus:                        2.400   Durbin-Watson:                   2.275
Prob(Omnibus):                  0.301   Jarque-Bera (JB):                1.964
Skew:                           0.161   Prob(JB):                        0.375
Kurtosis:                       3.537   Cond. No.                         4.92
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [25]:
results_ff5.params[0]

0.6483308637595689

Point estimation of alpha = 0.6483, and P = 0.067 > 0.05, so we cannot reject H0: alpha = 0. Therefore, alpha is NOT nonzero in the sampling period.

In [26]:
results_ff5.rsquared

0.770141599865072

R square is 0.770 now compared with 0.698 estimated in the three-factor model, so the five-factor model explains 0.2% more total variation than the three-factor model.

Q(4) best model based on adjusted R-square, AIC and BIC

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
X_s = StandardScaler(with_mean=True, with_std=True).fit_transform(X)
X_s

array([[ 2.01861685e-01, -8.92025004e-01,  4.05365894e-01,
        -4.84513462e-01,  6.52630006e-01],
       [ 5.67847818e-01,  6.89537125e-01,  6.21932536e-01,
        -1.25216599e+00,  6.73410724e-01],
       [-1.69004263e-01,  1.05297691e+00, -5.25490724e-01,
         1.04434073e+00,  4.30622664e-02],
       [ 4.26333180e-01, -1.81120815e-01, -7.53455610e-01,
         6.50838177e-01, -5.04163318e-01],
       [-5.91108270e-01, -2.57003846e-01, -5.29290139e-01,
         1.16690710e+00, -8.98996967e-01],
       [-7.05783925e-01,  5.45159673e-02,  9.76132978e-02,
         1.39268726e+00, -8.92070061e-01],
       [-8.54618286e-01, -4.12763753e-01, -1.72145151e-01,
         1.65717258e+00, -1.10680415e+00],
       [-1.73542491e+00, -1.20354482e+00, -7.49656196e-01,
         2.12808548e+00, -8.85489500e-02],
       [-2.12825003e+00, -1.36329857e+00, -4.07708866e-01,
         1.21206313e+00,  1.95454201e-01],
       [ 2.48561516e+00,  1.32855213e+00,  1.96398082e-01,
        -1.52310218e+00, -4.14113538e-01],
       [-3.47117515e-01, -8.92624081e-02, -2.39679748e-02,
         1.17980883e+00,  1.08902509e+00],
       [-9.82469442e-02, -8.52685643e-02,  7.58711468e-01,
         6.12133007e-01,  1.80249642e+00],
       [ 9.50913304e-01,  8.37309345e-01, -1.79743980e-01,
        -1.40053581e+00, -9.33631497e-01],
       [ 7.92319313e-01, -6.36419003e-01,  3.33177013e-01,
        -3.03889338e-01,  3.61353603e-02],
       [ 4.77571239e-01, -1.61151596e-01,  6.25731951e-01,
        -4.65160878e-01,  5.76434038e-01],
       [-4.86192245e-01, -1.69139283e-01, -1.18953344e-01,
         7.66953685e-01,  5.48726414e-01],
       [-1.78666297e+00, -1.39784532e-03, -1.87342810e-01,
         1.23786658e+00,  1.72630046e+00],
       [ 6.70323936e-01,  3.86005000e-01,  3.82569405e-01,
        -7.55449649e-01,  4.03261385e-01],
       [-8.84873140e-02, -1.09171719e+00,  1.50805105e-01,
         5.99231284e-01,  9.84775154e-02],
       [ 3.38496508e-01,  2.06282030e-01,  6.40929610e-01,
        -1.03928756e+00, -5.04163318e-01],
       [ 3.84854752e-01,  2.58201999e-01,  7.89106786e-01,
        -9.10270327e-01,  1.17214797e+00],
       [-7.10663741e-01, -3.00936127e-01,  1.51099559e+00,
        -9.74778943e-01,  1.83713095e+00],
       [-9.09272216e-02,  1.90306655e-01, -1.53148077e-01,
         1.73474419e-01,  6.52630006e-01],
       [ 6.66908065e-03,  7.97370907e-01,  1.49579793e+00,
        -1.18120651e+00,  6.45703099e-01],
       [ 1.07778850e+00,  1.98294343e-01,  5.57342485e-01,
        -1.36828150e+00,  1.14444034e+00],
       [ 3.35080638e-02, -6.92931893e-02,  2.53389303e-01,
        -4.52259154e-01,  5.14091883e-01],
       [ 7.02042734e-01,  3.82011156e-01,  9.00144682e-02,
         1.02514942e-01,  1.06824437e+00],
       [ 9.93855677e-02, -8.64068098e-01,  3.40775843e-01,
         1.79925281e-01,  3.89407573e-01],
       [ 4.04374012e-01,  8.45297032e-01,  1.18804534e+00,
        -1.36183064e+00, -5.66505473e-01],
       [-5.74028917e-01,  6.45604844e-01,  1.54604519e-01,
        -2.52282445e-01,  4.99891725e-02],
       [ 1.09730776e+00,  7.29475563e-01,  3.93967650e-01,
        -9.42524635e-01,  4.86384259e-01],
       [-9.42454958e-01,  1.85713735e-02, -8.63638639e-01,
         3.86352852e-01, -1.41158802e+00],
       [ 6.38605137e-01,  1.08892150e+00, -2.74729350e-01,
        -4.20004846e-01, -8.22800999e-01],
       [ 7.36201440e-01, -5.68523659e-01,  6.37130195e-01,
         1.70232862e+00,  7.08045255e-01],
       [ 4.80011146e-01,  6.05666406e-01,  2.45790474e-01,
         9.60640805e-02,  1.33112046e-01],
       [ 4.01934105e-01, -1.45176221e-01,  1.73601593e-01,
        -4.45808293e-01,  1.46965858e-01],
       [-1.08640950e+00,  2.70183530e-01, -5.82481946e-01,
        -2.59394520e+00, -9.75192934e-01],
       [ 8.60636725e-01,  8.24728737e-02,  4.06220762e-02,
        -2.32929860e-01, -2.82502322e-01],
       [-1.81203801e-01, -4.20751440e-01,  2.03531483e+00,
         1.23141572e+00,  1.42151659e+00],
       [-3.27598254e-01, -1.59494151e+00,  6.37130195e-01,
         2.12163462e+00,  7.35752879e-01],
       [ 2.16501130e-01, -7.12302035e-01,  1.35607445e-01,
        -1.29716075e-01, -5.73432379e-01],
       [ 3.55575861e-01,  1.25266910e+00, -9.61568554e-02,
        -1.25216599e+00, -1.23148846e+00],
       [-7.76541245e-01, -1.64686148e+00,  1.43206275e-01,
         5.28271807e-01,  4.44822822e-01],
       [ 7.53280792e-01,  1.46374374e-01, -4.29650487e-02,
        -4.84513462e-01, -3.86405913e-01],
       [-7.59461892e-01, -1.43119391e+00, -3.84912378e-01,
         7.02445070e-01, -3.17136852e-01],
       [ 3.31176785e-01,  1.49229972e+00, -4.45703014e-01,
        -3.23241923e-01,  2.37015638e-01],
       [ 3.43376323e-01, -8.88031160e-01, -1.01561523e+00,
         9.41126948e-01,  1.88527295e-01],
       [-2.93439549e-01,  1.16081069e+00,  9.79077524e-01,
        -8.52212573e-01,  7.14972161e-01],
       [-1.03517145e+00, -3.40874565e-01, -1.13719650e+00,
         9.47577810e-01, -1.04446200e+00],
       [ 1.21686323e+00,  1.74331280e-01, -5.06493650e-01,
        -7.81253095e-01, -1.12065796e+00],
       [-5.47189934e-01,  1.26065678e+00,  2.92238319e-02,
        -2.65022897e-02, -3.37917571e-01],
       [-1.34845558e-01, -1.17159407e+00,  8.57496252e-01,
        -3.94040129e-02, -3.37917571e-01],
       [ 5.54672318e-02,  3.58048093e-01, -2.48133446e-01,
        -1.20700996e+00, -4.83382599e-01],
       [-6.56985774e-01,  1.18876760e+00, -1.37950418e-01,
         1.54121835e-01, -9.75192934e-01],
       [ 1.01825475e-01, -1.79862754e+00, -1.40695495e+00,
         1.28318388e-01, -1.59861449e+00],
       [-1.75006436e+00,  1.46374374e-01,  1.21844065e+00,
         3.54098544e-01,  9.85121500e-01],
       [-1.02785172e+00, -1.08772335e+00,  3.82569405e-01,
         1.08949676e+00, -3.17136852e-01],
       [ 1.60968834e+00, -7.92178910e-01, -4.97090099e-03,
         5.41173530e-01,  5.14091883e-01],
       [-1.42165280e-01,  1.34852135e+00,  1.02267581e-02,
        -1.78113664e+00, -6.42701440e-01],
       [-8.05820135e-01, -1.14763100e+00, -8.02848002e-01,
         1.47670973e-01,  1.74673483e-01],
       [-1.68174695e+00, -1.34332935e+00,  9.63879865e-01,
         1.72168120e+00,  2.20425698e+00],
       [-2.98319364e-01,  3.78017312e-01, -5.81627078e-02,
         2.06357686e+00,  1.43537040e+00],
       [ 1.41449574e+00,  4.29937281e-01,  6.37130195e-01,
         3.67000267e-01,  9.84775154e-02],
       [-5.92084233e-02,  5.21795687e-01,  1.39701315e+00,
        -1.91015387e+00,  1.31761299e+00],
       [ 1.53063534e-01, -2.17065408e-01, -4.41903599e-01,
        -7.81253095e-01, -1.66788355e+00],
       [-2.88559734e-01,  1.98294343e-01, -3.92511207e-01,
         8.63716609e-01,  1.40766277e+00],
       [ 6.80083566e-01,  1.01703231e+00, -2.97525838e-01,
         7.73404547e-01, -7.11970501e-01],
       [-1.61684541e-01,  6.93530969e-01,  1.37801607e+00,
        -1.26506771e+00, -1.57818011e-01],
       [-2.15362507e-01,  7.53438626e-01, -2.78528764e-01,
        -1.47794615e+00,  1.12331328e-01],
       [-7.71661429e-01, -1.57497229e+00,  1.73516106e+00,
         5.66976976e-01,  2.64723262e-01],
       [ 9.02115153e-01,  2.81026816e+00,  3.32331644e+00,
        -2.26478999e-01,  2.66143278e+00],
       [ 1.60383257e-01,  2.06282030e-01,  1.49199852e+00,
         7.28248516e-01, -1.30110387e-01],
       [ 1.92102055e-01, -5.44560597e-01, -8.75036883e-01,
        -4.00652262e-01, -6.42701440e-01],
       [ 5.84927171e-01, -8.88031160e-01, -3.96310622e-01,
         2.18630451e-01, -1.15529249e+00],
       [-2.39761582e-01,  3.30091187e-01, -1.09160352e+00,
         3.34745959e-01, -5.66505473e-01],
       [-1.77299949e-02,  1.94300499e-01, -6.05278434e-01,
         1.08304590e+00, -1.01675437e+00],
       [-2.01699025e-02, -1.16360638e+00, -1.27777485e+00,
         5.66976976e-01, -1.05831581e+00],
       [-9.09272216e-02,  1.03700153e+00,  7.43513808e-01,
        -1.52955304e+00,  1.19258234e-01],
       [ 1.77462610e-01, -6.24437472e-01,  8.62150535e-02,
        -5.55472940e-01, -1.23529826e-02],
       [-2.37321675e-01, -7.00320504e-01, -6.35673753e-01,
         5.73589109e-02, -1.55705305e+00],
       [ 3.26296970e-01,  1.93162254e+00,  1.37041725e+00,
        -1.06509101e+00,  1.22063631e+00],
       [ 2.67739189e-01, -7.32271254e-01,  2.22993985e-01,
         5.21820945e-01, -2.08349791e+00],
       [ 4.80011146e-01, -1.21213158e-01,  1.39406860e-01,
         1.98616653e+00,  2.22815480e-02],
       [-2.26098100e-02, -3.88800690e-01,  1.92598667e-01,
         3.99254575e-01,  1.33146681e+00],
       [ 1.08022840e+00, -1.25147094e+00, -3.27921156e-01,
        -5.55472940e-01, -6.35774534e-01],
       [-1.16936636e+00,  1.66343593e-01, -2.44334031e-01,
         2.70237343e-01, -1.54319924e+00],
       [-8.54618286e-01,  1.47233050e+00,  9.38138830e-02,
        -3.36143646e-01,  1.46965858e-01],
       [-2.10482692e-01,  3.86005000e-01,  3.74970576e-01,
        -1.63276682e+00,  9.50486969e-01],
       [ 3.60455676e-01,  1.91165332e+00, -1.01941464e+00,
        -1.34892891e+00, -9.40558404e-01],
       [-1.61684541e-01,  3.38078874e-01, -7.11662048e-01,
         4.63763191e-01,  2.30088732e-01],
       [ 4.99530407e-01, -7.40258941e-01,  3.59772917e-01,
         9.15323502e-01,  3.06284699e-01],
       [ 5.62968003e-01,  2.90152749e-01, -1.31196958e+00,
        -2.58733307e-01, -1.68866427e+00],
       [-2.66600566e-01, -9.63914192e-01, -4.41903599e-01,
         3.47647682e-01,  1.03360984e+00],
       [-2.14532938e+00, -1.71875066e+00,  1.45780379e+00,
         5.92780423e-01,  2.58523682e+00],
       [ 1.35984181e-01, -2.92948440e-01,  3.10380525e-01,
        -4.65160878e-01,  3.68626854e-01],
       [-2.61135173e+00, -1.09171719e+00, -5.55886042e-01,
        -9.10109055e-02,  2.57796356e-01],
       [ 1.75852271e+00,  1.19276144e+00,  2.54244172e-02,
        -5.42571217e-01, -1.05138890e+00],
       [ 5.53208373e-01,  7.17494032e-01, -8.37042735e-01,
         3.15554646e-02, -9.75192934e-01],
       [-1.28501798e-02, -1.37528010e+00, -1.39935612e+00,
         4.96017499e-01, -5.31870942e-01],
       [ 6.87403289e-01, -4.28739128e-01,  9.82876939e-01,
         9.66930395e-01, -1.41851493e+00],
       [-1.96965604e+00, -5.92486722e-01, -7.57255025e-01,
        -3.81299677e-01,  1.31068609e+00],
       [ 1.40717602e+00,  1.78325124e-01, -6.95609521e-02,
         5.02468360e-01, -1.99379448e-01],
       [ 1.64287109e-02, -6.96326660e-01,  3.63572332e-01,
        -1.55519521e-01,  3.47846136e-01],
       [-9.03416437e-01, -1.26744632e+00, -1.63871925e+00,
         2.70237343e-01, -3.37917571e-01],
       [ 6.52268620e-02,  1.46374374e-01,  2.74200598e+00,
         1.10239849e+00,  2.43284488e+00],
       [ 2.23820853e-01,  1.30398999e-01, -5.55886042e-01,
         2.05728727e-01, -6.21920722e-01],
       [ 6.63004213e-01,  1.86312811e-01, -5.86281361e-01,
        -1.12959962e+00, -6.98116689e-01],
       [ 3.92174474e-01,  4.25943437e-01,  8.30900348e-01,
        -3.94040129e-02,  9.15852438e-01],
       [-3.03199179e-01, -1.71475682e+00, -2.18963439e+00,
        -8.39310850e-01, -1.42544183e+00],
       [-2.26976467e+00,  6.25036549e-02, -1.27777485e+00,
        -9.94131528e-01, -1.66095664e+00],
       [-3.53851660e+00, -3.23641129e+00, -5.08098903e+00,
        -1.11024704e+00,  9.15852438e-01],
       [ 3.03215445e+00,  1.05697075e+00, -3.35519986e-01,
         1.70877948e+00, -6.14993816e-01],
       [ 1.08266831e+00,  7.97370907e-01, -1.72610579e+00,
         5.47624392e-01, -2.09735173e+00],
       [ 3.14097433e-01,  8.09352438e-01, -6.50871412e-01,
         1.86537414e-02,  4.72530446e-01],
       [ 1.14122609e+00, -1.24348326e+00, -3.73514134e-01,
         1.73474419e-01,  7.63460504e-01],
       [ 1.57796955e+00, -3.24899190e-01, -9.73821667e-01,
         2.68285958e+00, -9.54412216e-01],
       [-1.16936636e+00,  2.65590610e-02, -8.59839224e-01,
        -9.61877220e-01, -1.24534227e+00],
       [-7.88740782e-01,  1.89567794e+00,  1.78835287e+00,
        -5.68374663e-01, -3.03283040e-01],
       [ 2.75400499e+00,  2.87416966e+00,  9.67679280e-01,
        -1.52310218e+00,  9.78194594e-01],
       [ 8.48437187e-01,  1.99951788e+00, -4.64700088e-01,
        -1.34247805e+00,  4.99891725e-02]])

In [31]:
from sklearn.linear_model import LinearRegression
from mlxtend.feature_selection import SequentialFeatureSelector as SFS

In [32]:
reg = LinearRegression().fit(X_s,Y)

In [33]:
def adjusted_r2(estimator, X, Y):
    '''
    Compute Adjusted R²
    '''
    n, p = X.shape
    Yhat = estimator.predict(X)
    RSS = np.sum((Y - Yhat)**2)
    TSS = np.sum((Y - np.mean(Y))**2)
    return 1 - RSS * (n-1) / (TSS * (n-p-1))

In [34]:
n, p = X_s.shape
sigma2 = np.sum((Y - reg.predict(X_s))**2) / (n-p-1)

In [35]:
ffs_adjR2 = SFS(LinearRegression(), k_features=(1,5), forward=True, verbose=2,
          scoring=adjusted_r2, cv=None, n_jobs=1).fit(X_s,Y)

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2026-02-28 15:03:17] Features: 1/5 -- score: 0.5635012834136526[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2026-02-28 15:03:17] Features: 2/5 -- score: 0.6931927939222309[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2026-02-28 15:03:17] Features: 3/5 -- score: 0.7406004186096364[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2026-02-28 15:03:17] Features: 4/5 -- score: 0.7521247050906386[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

[2026-02-28 15:03:17] Features: 5/5 -- score: 0.7600600910872244

In [36]:
pd.DataFrame.from_dict(ffs_adjR2.get_metric_dict()).T

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(0,)",[0.5635012834136526],0.563501,"(0,)",NaN,0.0,NaN
2,"(0, 2)",[0.6931927939222309],0.693193,"(0, 2)",NaN,0.0,NaN
3,"(0, 2, 3)",[0.7406004186096364],0.7406,"(0, 2, 3)",NaN,0.0,NaN
4,"(0, 2, 3, 4)",[0.7521247050906386],0.752125,"(0, 2, 3, 4)",NaN,0.0,NaN
5,"(0, 1, 2, 3, 4)",[0.7600600910872244],0.76006,"(0, 1, 2, 3, 4)",NaN,0.0,NaN

Adjusted R square reaches the top 0.76 from five-factor model. So five-factor model is the best model on the training set based on adjusted R square.

In [37]:
def AIC(estimator, X, Y):
    '''
    Compute AIC
    '''
    n, p = X.shape
    return n*np.log(sigma2)+2*(p+1)

In [38]:
def BIC(estimator, X, Y):
    '''
    Compute BIC
    '''
    n, p = X.shape
    return n*np.log(sigma2)+np.log(n)*(p+1)

In [39]:
ffs_AIC = SFS(LinearRegression(), k_features=(1,5), forward=True, verbose=2,
          scoring=AIC, cv=None, n_jobs=1).fit(X_s,Y)

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 1/5 -- score: 309.21478621504275[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 2/5 -- score: 311.21478621504275[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 3/5 -- score: 313.21478621504275[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 4/5 -- score: 315.21478621504275[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 5/5 -- score: 317.21478621504275

In [40]:
pd.DataFrame.from_dict(ffs_AIC.get_metric_dict()).T

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(0,)",[309.21478621504275],309.214786,"(0,)",NaN,0.0,NaN
2,"(0, 1)",[311.21478621504275],311.214786,"(0, 1)",NaN,0.0,NaN
3,"(0, 1, 2)",[313.21478621504275],313.214786,"(0, 1, 2)",NaN,0.0,NaN
4,"(0, 1, 2, 3)",[315.21478621504275],315.214786,"(0, 1, 2, 3)",NaN,0.0,NaN
5,"(0, 1, 2, 3, 4)",[317.21478621504275],317.214786,"(0, 1, 2, 3, 4)",NaN,0.0,NaN

In [41]:
ffs_BIC = SFS(LinearRegression(), k_features=(1,5), forward=True, verbose=2,
          scoring=BIC, cv=None, n_jobs=1).fit(X_s,Y)

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 1/5 -- score: 314.7897697006068[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 2/5 -- score: 319.57726144338886[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 3/5 -- score: 324.36475318617096[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 4/5 -- score: 329.152244928953[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

[2026-02-28 15:03:18] Features: 5/5 -- score: 333.93973667173503

In [42]:
pd.DataFrame.from_dict(ffs_BIC.get_metric_dict()).T

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(0,)",[314.7897697006068],314.78977,"(0,)",NaN,0.0,NaN
2,"(0, 1)",[319.57726144338886],319.577261,"(0, 1)",NaN,0.0,NaN
3,"(0, 1, 2)",[324.36475318617096],324.364753,"(0, 1, 2)",NaN,0.0,NaN
4,"(0, 1, 2, 3)",[329.152244928953],329.152245,"(0, 1, 2, 3)",NaN,0.0,NaN
5,"(0, 1, 2, 3, 4)",[333.93973667173503],333.939737,"(0, 1, 2, 3, 4)",NaN,0.0,NaN

In [43]:
def AIC_BIC_ratio(estimator, X, Y):
    '''
    Compute AIC/BIC
    '''
    n, p = X.shape
    aic = n*np.log(sigma2)+2*(p+1)
    bic = n*np.log(sigma2)+np.log(n)*(p+1)
    return -aic/bic

In [44]:
ffs_AIC_BIC_ratio = SFS(LinearRegression(), k_features=(1,5), forward=True, verbose=2,
          scoring=AIC_BIC_ratio, cv=None, n_jobs=1).fit(X_s,Y)

[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.0s finished

[2026-02-28 15:03:19] Features: 1/5 -- score: -0.9822898199936219[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

[2026-02-28 15:03:19] Features: 2/5 -- score: -0.9738326963859177[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.0s finished

[2026-02-28 15:03:19] Features: 3/5 -- score: -0.9656252201831294[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s finished

[2026-02-28 15:03:19] Features: 4/5 -- score: -0.9576564980836797[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s finished

[2026-02-28 15:03:19] Features: 5/5 -- score: -0.9499162614686583

In [45]:
pd.DataFrame.from_dict(ffs_AIC_BIC_ratio.get_metric_dict()).T

C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

,feature_idx,cv_scores,avg_score,feature_names,ci_bound,std_dev,std_err
1,"(0,)",[-0.9822898199936219],-0.98229,"(0,)",NaN,0.0,NaN
2,"(0, 1)",[-0.9738326963859177],-0.973833,"(0, 1)",NaN,0.0,NaN
3,"(0, 1, 2)",[-0.9656252201831294],-0.965625,"(0, 1, 2)",NaN,0.0,NaN
4,"(0, 1, 2, 3)",[-0.9576564980836797],-0.957656,"(0, 1, 2, 3)",NaN,0.0,NaN
5,"(0, 1, 2, 3, 4)",[-0.9499162614686583],-0.949916,"(0, 1, 2, 3, 4)",NaN,0.0,NaN

-AIC/BIC reaches the top -0.95 from five-factor model. So five-factor model is the best model on the training set based on AIC and BIC.

Q(5) prediction

In [46]:
newY = df_test['JPM']
newX = FF.loc[lambda df: (df.index>=202012) & (df.index<202512), ['Mkt-RF']] 
newX = sm.add_constant(newX)

In [49]:
Y_pred = results_s.get_prediction(newX)

In [50]:
Y_pred.predicted_mean # excess return prediction

array([  6.00394069,  -0.25879074,   3.57879788,   4.0451715 ,
         6.45698935,   0.22090784,   3.4721982 ,   1.62002869,
         3.76534733,  -6.02849864,   8.66893279,  -2.27085978,
         4.15177118,  -8.36036672,  -3.20360701,   3.93857181,
       -12.70430385,  -0.60523972, -11.35848284,  12.58647118,
        -5.18902613, -12.61102912,  10.30790293,   6.08389045,
        -8.66684082,   8.61563295,  -3.59003087,   3.15239914,
         0.67395649,   0.27420768,   8.44240846,   4.1117963 ,
        -3.3102067 ,  -7.13447036,  -4.36287857,  11.6670489 ,
         6.31041478,   0.8072061 ,   6.59023895,   3.61877276,
        -6.36162265,   5.59086692,   3.56547292,   1.46012916,
         1.97980262,   2.13970215,  -1.49801207,   8.48238334,
        -4.36287857,   3.56547292,  -3.40348142,  -8.68016578,
        -1.2848127 ,   7.90941004,   6.31041478,   2.47282616,
         2.29960167,   4.35164559,   2.44617624,  -0.33874051])

In [51]:
R2_oss = 1 - ((np.array(newY) - Y_pred.predicted_mean)**2).sum() / ((np.array(newY) - newY.mean())**2).sum()
R2_oss # Single-factor

-0.9078421028147323

In [52]:
newY = df_test['JPM']
newX = FF.loc[lambda df: (df.index>=202012) & (df.index<202512), ['Mkt-RF','SMB','HML']] 
newX = sm.add_constant(newX)

In [53]:
Y_pred = results_ff3.get_prediction(newX) 
Y_pred.predicted_mean # excess return prediction

array([  4.35859023,   3.75526693,  11.1998231 ,  11.68529729,
         5.30657579,   7.97767917,  -4.2705605 ,   0.1688488 ,
         3.73730559,   0.42597884,   7.79333704,  -1.8292948 ,
         7.61676316,   6.11813111,   0.89177425,   2.17301982,
        -4.50144344,   8.63909212, -15.64212278,   7.69679055,
        -3.8343656 , -10.67519995,  17.96799708,   7.51844725,
        -5.79843323,   4.39403145,  -3.411788  ,  -5.87049827,
         1.04914462,  -7.0666153 ,   8.0598842 ,   8.46154537,
        -3.58375772,  -4.29842319,  -3.16148421,  12.75391024,
        11.34443348,  -1.1772813 ,   3.01488308,   8.05684784,
        -5.5896272 ,   4.2955159 ,   0.32054885,   7.75757852,
         1.20797719,  -0.30350836,   0.12545406,   8.43265668,
        -6.40903432,   5.4386755 ,   2.46874188,  -4.24627077,
        -4.02645606,   4.75704233,   4.62572945,   1.53093412,
         7.23574589,   3.40545818,  -0.36019668,   4.14746819])

In [54]:
R2_oss = 1 - ((np.array(newY) - Y_pred.predicted_mean)**2).sum() / ((np.array(newY) - newY.mean())**2).sum()
R2_oss # Three-factor

-1.1898740004917334

In [55]:
newY = df_test['JPM']
newX = FF.loc[lambda df: (df.index>=202012) & (df.index<202512), ['Mkt-RF','SMB','HML','RMW','CMA']] 
newX = sm.add_constant(newX)

In [56]:
Y_pred = results_ff5.get_prediction(newX) 
Y_pred.predicted_mean # excess return prediction

array([  4.3958364 ,   2.98584788,  13.00087364,   4.1663078 ,
         5.3530218 ,   4.83531528,  -3.2991489 ,  -4.65505663,
         5.61291944,   2.73957734,   7.72548129, -10.92231497,
        -0.05969527,   5.31125919,   1.17435463,   1.79134097,
       -10.45223886,   6.67669573, -16.17466977,   9.85219089,
         0.67757131,  -7.56716978,  10.94513548,  -0.8568152 ,
        -8.52176768,   7.70452393,  -3.61220929,  -7.16165793,
        -2.90680398,  -1.6970488 ,   5.90543176,   8.95209058,
        -4.46808055,  -4.42917202,  -3.63447434,  18.49796734,
        12.74298106,   0.31535852,   6.34861369,   7.46624705,
        -5.53121682,   2.08384219,   1.6663827 ,   6.03326664,
         0.79435426,  -0.72621915,   1.97430307,  11.02820993,
        -6.95605855,  11.76711801,   2.52827892,  -4.51212451,
         1.23600915,   0.64640216,   6.85934426,   3.24549341,
         6.15930312,   8.10019988,   8.54036341,   2.77198343])

In [57]:
R2_oss = 1 - ((np.array(newY) - Y_pred.predicted_mean)**2).sum() / ((np.array(newY) - newY.mean())**2).sum()
R2_oss # Five-factor

-1.2272188292120858

The three model OOS R Square are all negative. So, it is hard to predict the market trend. There will be more likely to overestimate with more factors.